coinmarketcap/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CryptocurrencyViewSet, get

app_name = 'api'

v1_router = DefaultRouter()

v1_router.register('crypto', CryptocurrencyViewSet, basename='crypto')

urlpatterns = [
    path('', include(v1_router.urls)),
    path('update_crypto/', get, name='update_crypto'),
]

coinmarketcap/coinmarketcap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    patterns=[path('api/', include('coinmarketcap.urls'))],
    public=True,
    permission_classes=(permissions.AllowAny,),
)

apipatterns = [

    path('', include('users.urls')),
    path('', include('api.urls')),
]

urlpatterns = [
    path(
        'swagger-ui/',
        TemplateView.as_view(
            template_name='swaggerui/swaggerui.html',
            extra_context={'schema_url': 'openapi-schema'}
        ),
        name='swagger-ui'),
    re_path(
        r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json'),
    path('admin/', admin.site.urls),
    path('api/', include(apipatterns)),
    path('', include('crypto.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

coinmarketcap/crypto/urls.py
from django.urls import path

from .views import (AddFavoriteView, CryptoCreateView, CryptoDeleteView,
                    CryptoHome, CryptoUpdateView, FavoriteListView, Home,
                    RemoveFavoriteView, SearchHome)

app_name = 'crypto'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('search/', SearchHome.as_view(), name='search'),
    path('crypto/<slug:crypto_symbols>/', CryptoHome.as_view(),
         name='crypto_detail'),
    path('create/', CryptoCreateView.as_view(), name='create'),
    path('<int:id>/update/', CryptoUpdateView.as_view(), name='update'),
    path('<str:symbol>/delete/', CryptoDeleteView.as_view(), name='delete'),
    path('favorites/', FavoriteListView.as_view(), name='favorite_list'),
    path('favorites/add/<int:crypto_id>/', AddFavoriteView.as_view(),
         name='add_favorite'),
    path('favorites/remove/<int:crypto_id>/', RemoveFavoriteView.as_view(),
         name='remove_favorite'),
]

coinmarketcap/crypto/forms.py
from api.models import Cryptocurrency
from django import forms


class CryptoForm(forms.ModelForm):
    class Meta:
        model = Cryptocurrency
        fields = ('name', 'symbol', 'price', 'change_24h', 'volume_24h')

coinmarketcap/crypto/views.py
import requests
from api.models import Cryptocurrency, Favorite
from api.serializers import NewsSerializer
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import CryptoForm


class Home(ListView):
    model = Cryptocurrency
    template_name = 'crypto/index.html'
    context_object_name = 'crypto_home'
    paginate_by = 100


class SearchHome(ListView):
    model = Cryptocurrency
    template_name = 'crypto/search.html'
    context_object_name = 'crypto_home'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            search_list = Cryptocurrency.objects.filter(
                Q(name__icontains=query) | Q(symbol__icontains=query)
            )
        else:
            search_list = Cryptocurrency.objects.none()
        return search_list


class CryptoHome(DetailView):
    model = Cryptocurrency
    template_name = 'crypto/crypto.html'
    context_object_name = 'crypto'
    slug_url_kwarg = 'symbol'
    allow_empty = True

    def get_object(self, queryset=None):
        crypto_symbols = self.kwargs['crypto_symbols']
        return get_object_or_404(Cryptocurrency, symbol=crypto_symbols)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        crypto = self.get_object()
        api_key = settings.NEWS_API_KEY
        url = f'https://newsapi.org/v2/everything?q={crypto.name}'\
              f'&apiKey={api_key}'
        response = requests.get(url)
        data = response.json()
        if response.status_code == 200:
            articles = data['articles']
            for article in articles:
                if 'urlToImage' not in article:
                    article['urlToImage'] = None
            serializer = NewsSerializer(articles, many=True)
            context['articles'] = serializer.data
        else:
            context['error'] = data['message']
        return context


class CryptoCreateView(CreateView):
    model = Cryptocurrency
    form_class = CryptoForm
    template_name = 'crypto/create.html'
    success_url = reverse_lazy('crypto:home')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class CryptoUpdateView(UpdateView):
    model = Cryptocurrency
    form_class = CryptoForm
    template_name = 'crypto/update.html'
    slug_url_kwarg = 'simbol'
    success_url = reverse_lazy('crypto:home')

    def get_object(self, queryset=None):
        crypto_id = self.kwargs['id']
        return get_object_or_404(Cryptocurrency, id=crypto_id)

    def form_valid(self, form):
        form.instance.symbol = self.request.POST.get('symbol')
        form.instance.name = self.request.POST.get('name')
        form.instance.price = self.request.POST.get('price')
        form.instance.change_24h = self.request.POST.get('change_24h')
        form.instance.volume_24h = self.request.POST.get('volume_24h')
        self.object = form.save()
        return super().form_valid(form)


class CryptoDeleteView(DeleteView):
    model = Cryptocurrency
    template_name = 'crypto/delete.html'
    success_url = reverse_lazy('crypto:home')
    slug_url_kwarg = 'symbol'

    def get_object(self, queryset=None):
        crypto_symbol = self.kwargs['symbol']
        return get_object_or_404(Cryptocurrency, symbol=crypto_symbol)


class FavoriteListView(LoginRequiredMixin, View):
    def get(self, request):
        favorites = Favorite.objects.filter(user=request.user)
        return render(request, 'crypto/favorites.html',
                      {'favorites': favorites})


class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, crypto_id):
        crypto = get_object_or_404(Cryptocurrency, id=crypto_id)
        if not Favorite.objects.filter(user=request.user,
                                       crypto=crypto).exists():
            Favorite.objects.create(user=request.user, crypto=crypto)
        return redirect('crypto:favorite_list')


class RemoveFavoriteView(LoginRequiredMixin, View):
    def post(self, request, crypto_id):
        crypto = Cryptocurrency.objects.get(id=crypto_id)
        Favorite.objects.filter(user=request.user, crypto=crypto).delete()
        return redirect('crypto:favorite_list')

coinmarketcap/templates/crypto/add_favorite.html
{% extends 'base.html' %}

{% block content %}
    <h1>Добавить криптовалюту</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
    </form>
{% endblock %}

coinmarketcap/templates/crypto/create.html
{% extends "base.html" %}
{% block title %}Создать криптовалюту{% endblock %}

{% block content %}
<div class="container">
  <h1>Создать криптовалюту</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Создать</button>
  </form>
</div>
{% endblock %}

coinmarketcap/templates/crypto/crypto.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ crypto.name }}:</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Price</th>
            <th>Change 24h</th>
            <th>Volume 24h</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ crypto.id }}</td>
            <td>{{crypto.symbol}}</td>
            <td>{{crypto.name}}</td>
            <td>{{crypto.price}}</td>
            <td>{{crypto.change_24h}}</td>
            <td>{{crypto.volume_24h}}</td>
        </tr>
    </tbody>
</table>
{% if articles %}
  <h2>Последние новости:</h2>
  <ul>
    {% for article in articles %}
      <li>{{ article.title }}</li>
      <a href="{{ article.url }}">Ссылка на новость</a>
    {% endfor %}
  </ul>
{% endif %}
{% endblock  %}

coinmarketcap/templates/crypto/delete.html
{% extends "base.html" %}
{% block title %}Удалить криптовалюту{% endblock %}

{% block content %}
<div class="container">
  <h1>Удалить криптовалюту</h1>
  <p>Вы действительно хотите удалить криптовалюту "{{ object.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="symbol" value="{{ object.symbol }}">
    <button type="submit" class="btn btn-danger">Да, удалить</button>
    <a href="{% url 'crypto:home' %}" class="btn btn-secondary">Отмена</a>
  </form>
</div>
{% endblock %}

coinmarketcap/templates/crypto/favorites.html
{% extends 'base.html' %}

{% block content %}
    <h1>Избранное</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Symbol</th>
                <th>Name</th>
                <th>Price</th>
                <th>Change 24h</th>
                <th>Volume 24h</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for crypto in favorites %}
                <tr>
                    <td>{{ crypto.crypto.id }}</td>
                    <td>{{crypto.crypto.symbol}}</td>
                    <td><a href="{% url 'crypto:crypto_detail' crypto_symbols=crypto.crypto.symbol %}">{{ crypto.crypto.name }}</a></td>
                    <td>{{crypto.crypto.price}}</td>
                    <td>{{crypto.crypto.change_24h}}</td>
                    <td>{{crypto.crypto.volume_24h}}</td>
                    <td>
                    <form action="{% url 'crypto:remove_favorite' crypto.crypto.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn-delete">
                            Удалить из избранного
                        </button>
                    </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">Нет избранных криптовалют</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

coinmarketcap/templates/crypto/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-md-6">
    <div class="header-search">
      <form action="{% url 'crypto:search' %}" method="get">
        <input class="input" name="q" type="text" placeholder="Поиск">
        <button class="search-btn">Поиск</button>
      </form>
    </div>
  </div>
<h1>Список криптовалют:</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Price</th>
            <th>Change 24h</th>
            <th>Volume 24h</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for crypto in crypto_home  %}
        <tr>
            <td>{{ crypto.id }}</td>
            <td>{{crypto.symbol}}</td>
            <td><a href="{% url 'crypto:crypto_detail' crypto_symbols=crypto.symbol %}">{{ crypto.name }}</a></td>
            <td>{{crypto.price}}</td>
            <td>{{crypto.change_24h}}</td>
            <td>{{crypto.volume_24h}}</td>

            <td>
            <form action="{% url 'crypto:delete' crypto.symbol %}" method="GET">
                {% csrf_token %}
                <button type="submit" class="btn-delete">
                    Удалить
                </button>
            </form>
            </td>
            <td>
              <form action="{% url 'crypto:update' crypto.id %}" method="GET">
                  {% csrf_token %}
                  <button type="submit" class="btn-delete">
                      Обновить
                  </button>
              </form>
              </td>
            <td>
              <form action="{% url 'crypto:add_favorite' crypto.id %}" method="post">
                {% csrf_token %}
                <button type="submit">Добавить в избранное</button>
              </form>
            </td>
          {% endfor %}
        </tbody>
      </table>
      
{% if is_paginated %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current-page">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
  </div>
{% endif %}

{% endblock  %}

coinmarketcap/templates/crypto/search.html
{% extends 'base.html' %}

{% block content %}
<h1>Список найденных элементов:</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Price</th>
            <th>Change 24h</th>
            <th>Volume 24h</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for crypto in crypto_home  %}
        <tr>
            <td>{{ crypto.id }}</td>
            <td>{{crypto.symbol}}</td>
            <td>{{crypto.name}}</td>
            <td>{{crypto.price}}</td>
            <td>{{crypto.change_24h}}</td>
            <td>{{crypto.volume_24h}}</td>
            <td><a href="/delete/{{.ID}}"><div class="delete-icon"></div></a></td>
            <td><a href="/update/{{.ID}}"><div class="update-icon"></div></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock  %}

coinmarketcap/templates/crypto/update.html
{% extends "base.html" %}
{% block title %}Обновить криптовалюту{% endblock %}

{% block content %}
<div class="container">
  <h1>Обновить криптовалюту</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
  </form>
  <form method="post" action="{% url 'crypto:delete' object.symbol %}">
    {% csrf_token %}
    <input type="hidden" name="symbol" value="{{ object.symbol }}">
    <button type="submit" class="btn btn-danger">Удалить</button>
  </form>
</div>
{% endblock %}

coinmarketcap/templates/crypto/update_crypto.html
{% extends 'base.html' %}

{% block content %}
    <h1>Обновить криптовалюту "{{ form.instance.name }}"</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
    </form>
{% endblock %}