coinmarketcap/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CryptocurrencyViewSet, get

app_name = 'api'

v1_router = DefaultRouter()

v1_router.register('crypto', CryptocurrencyViewSet, basename='crypto')

urlpatterns = [
    path('', include(v1_router.urls)),
    path('update_crypto/', get, name='update_crypto'),
]

coinmarketcap/coinmarketcap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    patterns=[path('api/', include('coinmarketcap.urls'))],
    public=True,
    permission_classes=(permissions.AllowAny,),
)

apipatterns = [

    path('', include('users.urls')),
    path('', include('api.urls')),
]

urlpatterns = [
    path(
        'swagger-ui/',
        TemplateView.as_view(
            template_name='swaggerui/swaggerui.html',
            extra_context={'schema_url': 'openapi-schema'}
        ),
        name='swagger-ui'),
    re_path(
        r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json'),
    path('admin/', admin.site.urls),
    path('api/', include(apipatterns)),
    path('', include('crypto.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

coinmarketcap/crypto/urls.py
from django.urls import path

from .views import (AddFavoriteView, CryptoCreateView, CryptoDeleteView,
                    CryptoHome, CryptoUpdateView, FavoriteListView, Home,
                    RemoveFavoriteView, SearchHome)

app_name = 'crypto'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('search/', SearchHome.as_view(), name='search'),
    path('crypto/<slug:crypto_symbols>/', CryptoHome.as_view(),
         name='crypto_detail'),
    path('create/', CryptoCreateView.as_view(), name='create'),
    path('<int:id>/update/', CryptoUpdateView.as_view(), name='update'),
    path('<str:symbol>/delete/', CryptoDeleteView.as_view(), name='delete'),
    path('favorites/', FavoriteListView.as_view(), name='favorite_list'),
    path('favorites/add/<int:crypto_id>/', AddFavoriteView.as_view(),
         name='add_favorite'),
    path('favorites/remove/<int:crypto_id>/', RemoveFavoriteView.as_view(),
         name='remove_favorite'),
]

coinmarketcap/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Список элементов</title>
    <style>
        /* Стили для шапки */
        header {
            background-color: #2B2D42;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            color: #fff;
            font-size: 24px;
        }
        header a {
            color: #fff;
            text-decoration: none;
        }
        header ul {
            list-style: none;
            margin: 0;
            display: flex;
        }
        header li {
            margin-left: 20px;
        }
        
        table {
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        th:first-child, td:first-child {
            width: 10%;
        }
        th:nth-child(2), td:nth-child(2) {
            width: 30%;
        }
        th:last-child, td:last-child {
            width: 8%;
            text-align: center;
        }
        .delete-icon, .update-icon {
            width: 20px;
            height: 20px;
            cursor: pointer;
        }
        .delete-icon {
            background-image: url(delete-icon.png);
        }
        .update-icon {
            background-image: url(update-icon.png);
        }
        .delete-icon:hover, .update-icon:hover {
            opacity: 0.7;
        }
    </style>
</head>
<body>
    <header>
        <div>
            <a  href="{% url 'crypto:home' %}">CoinMarketCap</a>
            <a>|<a>
            <a  href="{% url 'api:update_crypto' %}">Обновить данные</a>
        </div>
        <div id="top-header">
            <div class="container">
              <ul class="header-links pull-right">
                {% if user.is_authenticated %}
                <li class="nav-item"> 
                    <a class="nav-link link-light " href="{% url 'crypto:create' %}">Добавить криптовалюту</a>
                </li>
                <li class="nav-item"> 
                    <a class="nav-link link-light " href="{% url 'crypto:favorite_list' %}">Избранное</a>
                </li>
                <li class="nav-item"> 
                  <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
                </li>
                <li><a href="#"><i class="fa fa-user-o"></i>Пользователь: {{ user.username }}</a></li>
              {% else %}
                <li class="nav-item"> 
                  <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
                </li>
                <li class="nav-item"> 
                  <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
                </li>
              {% endif %}
    </header>
    <main>
        {% block content %}
        {% endblock %} 
    </main>
</body>
</html>